apiVersion: v1
data:
  MYSQL_PASSWORD: {{ .Values.secret.data.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.data.MYSQL_ROOT_PASSWORD }}
  DOCUMENTDB_PASSWORD: {{ .Values.secret.data.DOCUMENTDB_PASSWORD }}
kind: Secret
metadata:
  name: {{ .Values.application.name }}-secret
type: Opaque
