apiVersion: v1
kind: Service
metadata:
  name: fast-n-foodious-ms-pagamento-svc
spec:
  selector:
    app: fast-n-foodious-ms-pagamento
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 3306

