apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-n-foodious-ms-pagamento
spec:
  selector:
    matchLabels:
      app: fast-n-foodious-ms-pagamento
  template:
    metadata:
      labels:
        app: fast-n-foodious-ms-pagamento
    spec:
      containers:
      - name: fast-n-foodious-ms-pagamento
        image: ottero/fast-n-foodious-ms-pagamento:latest
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            port: 3002
            path: /api
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: 3002
            path: /api
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 3002
        envFrom:
          - configMapRef:
              name: fast-n-foodious-ms-pagamento-env
        env:
          - name: DOCUMENTDB_URI
            valueFrom:
              configMapKeyRef:
                name: fast-n-foodious-ms-pagamento-env
                key: DOCUMENTDB_URI
          - name: DOCUMENTDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fast-n-foodious-ms-pagamento-secret
                key: DOCUMENTDB_PASSWORD
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: fast-n-foodious-ms-pagamento-env
                key: SERVER_PORT
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-pagamento
# spec:
#   selector:
#     matchLabels:
#       app: mysql-pagamento
#   template:
#     metadata:
#       labels:
#         app: mysql-pagamento
#     spec:
#       containers:
#       - name: mysql-pagamento
#         image: mysql:8.0
#         resources:
#           limits:
#             memory: "768Mi"
#             cpu: "500m"
#         ports:
#           - containerPort: 3306
#         livenessProbe:
#           tcpSocket:
#             port: 3306
#           initialDelaySeconds: 10
#           periodSeconds: 10
#           successThreshold: 1
#           failureThreshold: 3
#         readinessProbe:
#           tcpSocket:
#             port: 3306
#           initialDelaySeconds: 30
#           periodSeconds: 10
#           successThreshold: 1
#           failureThreshold: 3
#         envFrom:
#           - configMapRef:
#               name: fast-n-foodious-ms-pagamento-env
#         env:
#           - name: MYSQL_ROOT_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: fast-n-foodious-ms-pagamento-secret
#                 key: MYSQL_ROOT_PASSWORD
#           - name: MYSQL_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: fast-n-foodious-ms-pagamento-secret
#                 key: MYSQL_PASSWORD
#         volumeMounts:
#           - name: fast-n-foodious-ms-pagamento-mysql-init
#             mountPath: /docker-entrypoint-initdb.d
#           - name: fast-n-foodious-ms-pagamento-volume
#             mountPath: /var/lib/mysql-pagamento
#       volumes:
#         - name: fast-n-foodious-ms-pagamento-volume
#           persistentVolumeClaim:
#             claimName: fast-n-foodious-ms-pagamento-pvc
#         - name: fast-n-foodious-ms-pagamento-mysql-init
#           configMap:
#             name: mysql-pagamento-env
#             items:
#               - key: init.sql
#                 path: 1-init.sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.5
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
        ports:
          - containerPort: 27017
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: fast-n-foodious-ms-pagamento-env
                key: DOCUMENTDB_USER
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: fast-n-foodious-ms-pagamento-env
                key: DOCUMENTDB_DATABASE                
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fast-n-foodious-ms-pagamento-secret
                key: DOCUMENTDB_PASSWORD
        volumeMounts:
          - name: fast-n-foodious-ms-pagamento-volume
            mountPath: /data/mongodb
          - name: mongodb-scripts
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: fast-n-foodious-ms-pagamento-volume
          persistentVolumeClaim:
            claimName: fast-n-foodious-ms-pagamento-pvc
        - name: mongodb-scripts
          configMap:
            name: fast-n-foodious-ms-pagamento-env
            items:
            - key: ensure-users.sh
              path: ensure-users.sh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 4566
        livenessProbe:
          tcpSocket:
            port: 4566
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 4566
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: fast-n-foodious-ms-pagamento-env
        env:
          - name: DEBUG
            value: '0'
          - name: SERVICES
            value: sqs,ses
          - name: MAIN_CONTAINER_NAME
            value: localstack
        volumeMounts:
          - name: fast-n-foodious-ms-pagamento-localstack-init
            mountPath: /etc/localstack/init/ready.d
          - name: fast-n-foodious-localstack
            mountPath: /var/lib/localstack
      volumes:
        - name: fast-n-foodious-localstack
          persistentVolumeClaim:
            claimName: fast-n-foodious-ms-pagamento-pvc
        - name: fast-n-foodious-ms-pagamento-localstack-init
          configMap:
            name: mysql-pagamento-env
            defaultMode: 0777
            items:
              - key: init.sh
                path: init-queues.sh              