apiVersion: v1
kind: Service
metadata:
  name: fast-n-foodious-ms-pagamento
spec:
  selector:
    app: fast-n-foodious-ms-pagamento
  type: LoadBalancer
  ports:
  - port: 3002
    nodePort: 30002
    targetPort: 3002
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-pagamento
# spec:
#   selector:
#     app: mysql-pagamento
#   ports:
#   - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
  - port: 4566  