apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-n-foodious-ms-pagamento-env
data:
  MYSQL_DATABASE: FAST_N_FOODIOUS
  MYSQL_HOST: mysql-pagamento
  MYSQL_PORT: '3306'
  MYSQL_USER: fnf_user
  MYSQL_ROOT_HOST: '%'
  NODE_ENV: prod
  SERVER_PORT: '3002'
  DATABASE_ENGINE: nosql
  DOCUMENTDB_URI: mongodb://fnf_user:fnfpass@mongodb:27017/pagamento-db
  DOCUMENTDB_USER: fnf_user
  DOCUMENTDB_DATABASE: pagamento-db
  DOCUMENTDB_DATABASE_TLS_CA_FILE: global-bundle.pem
  ensure-users.sh: |
      set -e

      mongosh <<EOF
      use $MONGO_INITDB_DATABASE

      print('mongodb startup script..');
      db.createUser({
        user: '$MONGO_INITDB_ROOT_USERNAME',
        pwd: '$MONGO_INITDB_ROOT_PASSWORD',
        roles: [{
          role: 'readWrite',
          db: '$MONGO_INITDB_DATABASE'
        }]
      })
      print('user created..');

      EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-pagamento-env
data:
  init.sql: |
    -- Criação de banco de dados
    CREATE DATABASE IF NOT EXISTS FAST_N_FOODIOUS;

    -- Configuração de permissão para usuário da aplicação
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES ON FAST_N_FOODIOUS.* TO 'fnf_user'@'%';
    FLUSH PRIVILEGES;

    USE FAST_N_FOODIOUS;

    --
    -- CRIAÇÃO DE TABELAS
    --

    -- Tabela PAGAMENTO
    CREATE TABLE IF NOT EXISTS PAGAMENTO (
                                          ID INT AUTO_INCREMENT PRIMARY KEY,
                                          PEDIDO_ID INT NOT NULL,
                                          TRANSACAO_ID VARCHAR(255) NOT NULL,
                                          ESTADO_PAGAMENTO INT NOT NULL,
                                          TOTAL DECIMAL(8,2) NOT NULL,
                                          DATA_HORA_PAGAMENTO DATETIME NULL
    );
